swagger: "2.0"
info:
  title: "Brand 1"
  version: "0.0.1"
paths:
  /brands:
    get:
      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
