// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetBrandsOKCode is the HTTP code returned for type GetBrandsOK
const GetBrandsOKCode int = 200

/*GetBrandsOK Successful response

swagger:response getBrandsOK
*/
type GetBrandsOK struct {

	/*
	  In: Body
	*/
	Payload *GetBrandsOKBody `json:"body,omitempty"`
}

// NewGetBrandsOK creates GetBrandsOK with default headers values
func NewGetBrandsOK() *GetBrandsOK {

	return &GetBrandsOK{}
}

// WithPayload adds the payload to the get brands o k response
func (o *GetBrandsOK) WithPayload(payload *GetBrandsOKBody) *GetBrandsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get brands o k response
func (o *GetBrandsOK) SetPayload(payload *GetBrandsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBrandsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
